recipes.remove(<flansmod:dwBrassDust>);
recipes.remove(<flansmod:gunBox.extractorBlock>);
recipes.remove(<flansmod:dwABTArmorBox>);
recipes.remove(<minecraft:dirt:2>);
recipes.remove(<openmodularturrets:hardWallTierFive>);
recipes.remove(<openmodularturrets:hardWallTierFour>);
recipes.remove(<openmodularturrets:hardWallTierThree>);
recipes.remove(<openmodularturrets:hardWallTierTwo>);
recipes.remove(<openmodularturrets:hardWallTierOne>);
recipes.remove(<flansmod:dwWingbreakerPonyBoots>);
recipes.remove(<flansmod:dwWingbreakerPonyLegs>);
recipes.remove(<flansmod:dwWingbreakerPonyBody>);
recipes.remove(<FFS:blockValve>);
recipes.remove(<flansmod:dwWingbreakerPonyHead>);
recipes.remove(<flansmod:dwGasMask>);
recipes.remove(<IronChest:diamondObsidianUpgrade>);
recipes.remove(<IronChest:diamondCrystalUpgrade>);
recipes.remove(<IronChest:goldDiamondUpgrade>);
recipes.remove(<IronChest:ironGoldUpgrade>);
recipes.remove(<IronChest:silverGoldUpgrade>);
recipes.remove(<IronChest:copperIronUpgrade>);
recipes.remove(<IronChest:copperSilverUpgrade>);
recipes.remove(<IronChest:woodIronUpgrade>);
recipes.remove(<IronChest:woodCopperUpgrade>);
recipes.remove(<IronChest:BlockIronChest:5>);
recipes.remove(<powersuits:powerArmorComponent:14>);
recipes.remove(<powersuits:powerArmorComponent:18>);
recipes.remove(<powersuits:powerArmorComponent:19>);
recipes.remove(<powersuits:powerArmorComponent:11>);
recipes.remove(<powersuits:powerArmorComponent:12>);
recipes.remove(<powersuits:powerArmorComponent:15>);
recipes.remove(<powersuits:powerArmorComponent:20>);
recipes.remove(<powersuits:powerArmorComponent:17>);
recipes.remove(<powersuits:powerArmorComponent:7>);
recipes.remove(<powersuits:powerArmorComponent:6>);
recipes.remove(<powersuits:powerArmorComponent:5>);
recipes.remove(<powersuits:powerArmorComponent:4>);
recipes.remove(<powersuits:powerArmorComponent:10>);
recipes.remove(<powersuits:powerArmorComponent:9>);
recipes.remove(<powersuits:powerArmorComponent:2>);
recipes.remove(<powersuits:powerArmorComponent>);
recipes.remove(<powersuits:powerArmorComponent:1>);
recipes.remove(<powersuits:powerArmorComponent:3>);
recipes.remove(<powersuits:item.powerArmorHelmet>);
recipes.remove(<powersuits:item.powerArmorBoots>);
recipes.remove(<powersuits:item.powerArmorLeggings>);
recipes.remove(<powersuits:item.powerArmorChestplate>);
recipes.remove(<powersuits:item.powerFist>);
recipes.remove(<powersuits:tile.tinkerTable>);
recipes.remove(<mffs:BlockCoercionDeriver>);
recipes.remove(<mffs:BlockForceFieldProjector>);
recipes.remove(<mffs:BlockFortronCapacitor>);
recipes.remove(<mffs:BlockInterdictionMatrix>);
recipes.remove(<mffs:focusMatrix>);
recipes.remove(<IronChest:BlockIronChest:6>);
recipes.remove(<IronChest:BlockIronChest:4>);
recipes.remove(<IronChest:BlockIronChest:3>);
recipes.remove(<IronChest:BlockIronChest:2>);
recipes.remove(<IronChest:BlockIronChest:1>);
recipes.remove(<IronChest:BlockIronChest>);
recipes.remove(<flansmod:dwHighSteelIngot>);
recipes.remove(<flansmod:gunBox.penbarUrbanPolice>);
recipes.remove(<NuclearCraft:material:7>);
recipes.remove(<NuclearCraft:material:22>);
recipes.remove(<flansmod:dwWingbreakerBoots>);
recipes.remove(<malisisdoors:player_sensor>);
recipes.remove(<flansmod:dwWingbreakerLegs>);
recipes.remove(<flansmod:dwWingbreakerBody>);
recipes.remove(<flansmod:dwWingbreakerHead>);
recipes.remove(<flansmod:dwAssaultHead>);
recipes.remove(<flansmod:dwAssaultBody>);
recipes.remove(<Mekanism:Jetpack>);
recipes.remove(<attainedDrops:plantSeed>);
recipes.remove(<nnn:NetherGate>);
recipes.remove(<flansmod:dwUnfiredFiberglass>);
recipes.remove(<malisisdoors:item.forcefieldItem>);
recipes.remove(<Mekanism:AtomicDisassembler>);
recipes.remove(<flansmod:flansWorkbench:1>);
recipes.remove(<flansmod:flansWorkbench>);
recipes.remove(<flansmod:dwAssaultLegs>);
recipes.remove(<flansmod:dwAssaultBoots>);
recipes.remove(<flansmod:dwCasualBody>);
recipes.remove(<flansmod:dwCasualLegs>);
recipes.remove(<NuclearCraft:pistol>);
recipes.remove(<NuclearCraft:dUBullet>);
recipes.remove(<DefenseTech:explosives:21>);
recipes.remove(<DefenseTech:explosives:22>);
recipes.remove(<Mekanism:MachineBlock2:1>);
recipes.remove(<Mekanism:MachineBlock2:15>);
recipes.remove(<Mekanism:Robit>);
recipes.remove(<NuclearCraft:parts:5>);
recipes.remove(<row:item.row.stock:9>);
recipes.remove(<row:item.row.stock:8>);
recipes.remove(<Mekanism:MachineBlock2>);
recipes.remove(<row:item.row.enginewheel>);
recipes.remove(<row:item.row.cartwheel>);
recipes.remove(<row:item.row.boiler>);
recipes.remove(<row:item.row.funnellarge>);
recipes.remove(<row:item.row.funnelsmall>);
recipes.remove(<row:item.row.traincabin>);
recipes.remove(<row:item.row.light>);
recipes.remove(<row:item.row.battery>);
recipes.remove(<DefenseTech:explosives:15>);
recipes.remove(<DefenseTech:missile:15>);
recipes.remove(<DefenseTech:missile:21>);
recipes.remove(<DefenseTech:missile:27>);
recipes.remove(<flansmod:dwValkyrieHead>);
recipes.remove(<flansmod:dwValkyrieLegs>);
recipes.remove(<flansmod:dwValkyrieBody>);
recipes.remove(<flansmod:dwValkyrieBoots>);
recipes.remove(<flansmod:dwContractorBody>);
recipes.remove(<flansmod:dwContractorHead>);
recipes.remove(<flansmod:dwContractorBoots>);
recipes.remove(<flansmod:dwContractorLegs>);
recipes.remove(<flansmod:dwFrostweatherBody>);
recipes.remove(<flansmod:dwSpikedHead>);
recipes.remove(<flansmod:dwRiotHelmet>);
recipes.remove(<flansmod:dwPenbarHeadgear>);
recipes.remove(<flansmod:dwSunnyGear>);
recipes.remove(<flansmod:dwLupineArmorStandard>);
recipes.remove(<flansmod:dwLupineArmorBasic>);
recipes.remove(<flansmod:dwLupineArmorTactical>);
recipes.remove(<flansmod:dwLupineArmorStandardB>);
recipes.remove(<flansmod:dwCasualBoots>);
recipes.remove(<flansmod:dwTacticalBoots>);
recipes.remove(<flansmod:dwTacticalLegs>);
recipes.remove(<flansmod:dwTacticalBody>);
recipes.remove(<flansmod:dwTacticalHead>);
recipes.remove(<flansmod:dwChamberlainBoots>);
recipes.remove(<flansmod:dwChamberlainLegs>);
recipes.remove(<flansmod:dwChamberlainBody>);
recipes.remove(<flansmod:dwChamberlainHead>);
recipes.remove(<flansmod:dwCompSteelIngot>);
recipes.remove(<flansmod:dwDustIron>);
recipes.remove(<Mekanism:ArmoredJetpack>);
recipes.remove(<Mekanism:AtomicDisassembler>);
recipes.remove(<mffs:cardFrequency>);

<ezwastelands:ezwastelandblock>.displayName = "Dried Dirt";
<SimpleAchievements:sa.achievementBook>.displayName = "Journey Book";
<flansmod:gunBox.ambirconTechnologies>.addTooltip(format.yellow("Used for crafting guns and other weapon related stuff"));
<flansmod:gunBox.lupineMilitary>.addTooltip(format.yellow("Used for crafting guns and other weapon related stuff"));
<flansmod:gunBox.penbarUrbanPolice>.addTooltip(format.yellow("Used for crafting guns and other weapon related stuff"));
<flansmod:gunBox.skymareCorporation>.addTooltip(format.yellow("Used for crafting guns and other weapon related stuff"));
<flansmod:flansWorkbench:1>.addTooltip(format.yellow("Used for customizing your weapon of choice"));
<flansmod:gunBox.dwMiscBox>.addTooltip(format.yellow("Used for creating upgrades for your weapons"));
<flansmod:gunBox.vehicleAssemblyBlock>.addTooltip(format.yellow("Used for crafting vehicles"));
<flansmod:flansWorkbench>.addTooltip(format.yellow("Used for crafting vehicle parts"));
<flansmod:gunBox.extractorBlock>.displayName = "Empty Machine Casing";
<flansmod:dwBrassDust>.displayName = "Copper and Iron Mix";
<NuclearCraft:pistol>.displayName = "Pistol {Disabled}";
<flansmod:dwZincPellets>.displayName = "Iron Pellets";
<minecraft:skull:2>.displayName = "Ghoul Head";
<nnn:NetherGate>.displayName = "Interdimensional Gate";
<nnn:NetherGate>.addTooltip(format.yellow("Used for crafting interdimensional stuff"));
<attainedDrops:plantSeed>.displayName = "Life Essence";
<attainedDrops:plantSeed>.addTooltip(format.yellow("Can be used for crafting or when planted on vitalized soil"));
<attainedDrops:plantSeed>.addTooltip(format.yellow("it can be used for farming mob drops"));
<DefenseTech:explosives:15>.displayName = "Invalid Bomb";
<DefenseTech:explosives:21>.displayName = "Invalid Bomb 2";
<Mekanism:Flamethrower>.displayName = "Hydrogen Flamethrower";
<DefenseTech:explosives:15>.addTooltip(format.darkRed("Do not use!!"));
<DefenseTech:explosives:21>.addTooltip(format.darkRed("Do not use!!"));
<NuclearCraft:EMP>.addTooltip(format.darkRed("Do not use!!"));
<NuclearCraft:EMP>.displayName = "Invalid Bomb 3";
<Mekanism:Ingot:4>.addTooltip(format.yellow("Obtainable through smelting the dust"));
<Mekanism:Ingot:4>.displayName = "Enriched Steel Ingot";
<Mekanism:OtherDust:1>.displayName = "Enriched Steel Dust";
<Mekanism:BasicBlock:5>.displayName = "Enriched Steel Block";
<Mekanism:BasicBlock:8>.displayName = "Enriched Steel Casing";
<attainedDrops:blockMobBulb:4>.displayName = "RadScorpion Eye Bulb";
<minecraft:spider_eye>.displayName = "RadScorpion Eye";
<minecraft:fermented_spider_eye>.displayName = "Fermented RadScorpion Eye";

recipes.addShaped(<flansmod:dwBrassDust>, [[<ore:dustIron>, <ore:dustCopper>], [<ore:dustCopper>, <ore:dustIron>]]);
recipes.addShaped(<openmodularturrets:serialPortAddon>, [[<minecraft:iron_ingot>, <minecraft:iron_ingot>, <minecraft:iron_ingot>], [<minecraft:iron_ingot>, <OpenComputers:case1>, <minecraft:iron_ingot>], [<minecraft:iron_ingot>, <minecraft:iron_ingot>, <minecraft:iron_ingot>]]);
recipes.addShaped(<flansmod:dwHighSteelIngot>, [[<flansmod:dwMidSteelIngot>, <aobd:shardMagnesium>, <flansmod:dwMidSteelIngot>], [<minecraft:diamond>, <ore:ingotTough>, <ore:gemDiamond>], [<flansmod:dwMidSteelIngot>, <aobd:shardMagnesium>, <flansmod:dwMidSteelIngot>]]);
recipes.addShaped(<NuclearCraft:material:7> * 25, [[<NuclearCraft:blockBlock:7>]]);
recipes.addShaped(<malisisdoors:player_sensor> * 2, [[null, <ore:torchRedstoneActive>, null], [<flansmod:dwSteelIngot>, <ore:oc:motionSensor>, <flansmod:dwSteelIngot>], [null, <ore:torchRedstoneActive>, null]]);
recipes.addShaped(<flansmod:gunBox.penbarUrbanPolice>, [[<ore:ingotIron>, <ore:ingotIron>, <ore:ingotIron>], [<minecraft:iron_bars>, <flansmod:dwBallisticGlass>, <minecraft:iron_bars>], [<flansmod:dwSteelIngot>, <flansmod:dwSteelIngot>, <flansmod:dwSteelIngot>]]);
recipes.addShaped(<Mekanism:Jetpack>, [[<flansmod:dwMidSteelIngot>, <ore:circuitAdvanced>, <flansmod:dwMidSteelIngot>], [<ore:ingotTough>, <Mekanism:GasTank>.withTag({tier: 3}), <ore:ingotTough>], [null, <ore:ingotTough>, null]]);
recipes.addShaped(<NuclearCraft:nuclearGrenade>, [[<minecraft:string>], [<flansmod:dwBlaziteFuelKit>], [<NuclearCraft:nuke>]]);
recipes.addShaped(<minecraft:feather> * 12, [[<attainedDrops:plantSeed>, <minecraft:wool>]]);
recipes.addShaped(<minecraft:skull>, [[<flansmod:dwCarbonKnife>.giveBack(<flansmod:dwCarbonKnife>), <minecraft:skull:2>]]);
recipes.addShaped(<minecraft:water_bucket>, [[<flansmod:dwElectricDust>, <RedLogic:redlogic.plainBlock:1>, <flansmod:dwElectricDust>], [<RedLogic:redlogic.plainBlock:1>, <WLM:item.toxicWasteBucket>, <RedLogic:redlogic.plainBlock:1>], [<flansmod:dwElectricDust>, <RedLogic:redlogic.plainBlock:1>, <flansmod:dwElectricDust>]]);
recipes.addShaped(<minecraft:egg> * 3, [[<attainedDrops:plantSeed>, <minecraft:slime_ball>, <attainedDrops:plantSeed>], [<minecraft:slime_ball>, <attainedDrops:plantSeed>, <minecraft:slime_ball>], [<attainedDrops:plantSeed>, <minecraft:slime_ball>, <attainedDrops:plantSeed>]]);
recipes.addShaped(<minecraft:cactus>, [[<minecraft:deadbush>, <minecraft:deadbush>, <minecraft:deadbush>], [<minecraft:deadbush>, <attainedDrops:plantSeed>, <minecraft:deadbush>], [<minecraft:deadbush>, <minecraft:deadbush>, <minecraft:deadbush>]]);
recipes.addShaped(<minecraft:deadbush>, [[<minecraft:stick>, <ore:stickWood>, <ore:stickWood>], [<ore:stickWood>, <minecraft:stick>, <ore:stickWood>], [null, <ore:stickWood>, null]]);
recipes.addShaped(<minecraft:snowball>, [[<minecraft:clay_ball>, <attainedDrops:plantSeed>]]);
recipes.addShaped(<minecraft:packed_ice>, [[<attainedDrops:plantSeed>, <attainedDrops:plantSeed>, <attainedDrops:plantSeed>], [null, <minecraft:water_bucket>.giveBack(<minecraft:bucket>), null]]);
recipes.addShaped(<minecraft:ice>, [[<attainedDrops:plantSeed>], [<minecraft:water_bucket>.giveBack(<minecraft:bucket>)]]);
recipes.addShaped(<minecraft:dye> * 2, [[<attainedDrops:plantSeed>, <ore:gemCoal>, <attainedDrops:plantSeed>]]);
recipes.addShaped(<minecraft:reeds> * 3, [[null, <ore:stickWood>, <attainedDrops:plantSeed>], [<ore:stickWood>, <attainedDrops:plantSeed>, <ore:stickWood>], [<attainedDrops:plantSeed>, <ore:stickWood>, null]]);
recipes.addShaped(<minecraft:dye:15>, [[<flansmod:dwZincPellets>, <flansmod:dwCopperPellets>, <flansmod:dwZincPellets>], [<flansmod:dwCopperPellets>, <CarpentersBlocks:itemCarpentersHammer>.giveBack(<CarpentersBlocks:itemCarpentersHammer>), <flansmod:dwCopperPellets>], [<flansmod:dwZincPellets>, <flansmod:dwCopperPellets>, <flansmod:dwZincPellets>]]);
recipes.addShaped(<attainedDrops:plantSeed>, [[<minecraft:leather>, <minecraft:dye:15>], [<minecraft:wheat_seeds>, null]]);
recipes.addShaped(<flansmod:dwCopperPellets> * 9, [[<Mekanism:Dust:3>]]);
recipes.addShaped(<flansmod:dwZincPellets> * 9, [[<ore:dustIron>]]);
recipes.addShaped(<minecraft:grass>, [[<minecraft:wheat_seeds>], [<minecraft:dirt>]]);
recipes.addShaped(<minecraft:dirt>, [[<ezwastelands:ezwastelandblock>], [<minecraft:water_bucket>.giveBack(<minecraft:bucket>)]]);
recipes.addShaped(<nnn:NetherGate>, [[<ore:oreObsidian>, <ore:oreObsidian>, <ore:oreObsidian>], [<ore:oreObsidian>, <ore:alloyElite>, <ore:oreObsidian>], [<ore:oreObsidian>, <ore:oreObsidian>, <ore:oreObsidian>]]);
recipes.addShaped(<flansmod:dwUnfiredFiberglass> * 2, [[<ore:sand>, <minecraft:hardened_clay>, <ore:sand>], [<minecraft:hardened_clay>, <flansmod:dwElectricDust>, <minecraft:hardened_clay>], [<ore:sand>, <minecraft:hardened_clay>, <ore:sand>]]);
recipes.addShaped(<malisisdoors:item.forcefieldItem>, [[null, <DefenseTech:laserDesignator>, null], [<ore:alloyElite>, <ore:circuitElite>, <ore:alloyElite>], [<Mekanism:CompressedObsidian>, <Mekanism:CompressedObsidian>, <Mekanism:CompressedObsidian>]]);
recipes.addShaped(<flansmod:flansWorkbench:1>, [[<flansmod:dwMidSteelIngot>, <flansmod:dwElectricDust>, <flansmod:dwMidSteelIngot>], [<flansmod:dwElectricDust>, <ore:circuitAdvanced>, <flansmod:dwElectricDust>], [<flansmod:dwMidSteelIngot>, <flansmod:dwElectricDust>, <flansmod:dwMidSteelIngot>]]);
recipes.addShaped(<flansmod:flansWorkbench>, [[<flansmod:dwIngotBrass>, <flansmod:dwPaperVehicle>, <flansmod:dwIngotBrass>], [<flansmod:dwMidSteelIngot>, <flansmod:dwEngineDynamic>, <flansmod:dwMidSteelIngot>], [<flansmod:dwMidSteelIngot>, <flansmod:dwEngineSteam>, <flansmod:dwMidSteelIngot>]]);
recipes.addShaped(<NuclearCraft:material:7>, [[null, <flansmod:dwElectricDust>, null], [<ore:dustDiamond>, <flansmod:dwMidSteelIngot>, <ore:dustDiamond>], [null, <flansmod:dwElectricDust>, null]]);
recipes.addShaped(<NuclearCraft:antimatterBomb>, [[<NuclearCraft:antimatter>, <NuclearCraft:nuke>, <NuclearCraft:antimatter>], [<NuclearCraft:nuke>, <NuclearCraft:antimatter>, <NuclearCraft:nuke>], [<NuclearCraft:antimatter>, <NuclearCraft:nuke>, <NuclearCraft:antimatter>]]);
recipes.addShaped(<DefenseTech:explosives:22>, [[<minecraft:nether_star>, <NuclearCraft:antimatterBomb>, <minecraft:nether_star>], [<NuclearCraft:antimatterBomb>, <minecraft:nether_star>, <NuclearCraft:antimatterBomb>], [<minecraft:nether_star>, <NuclearCraft:antimatterBomb>, <minecraft:nether_star>]]);
recipes.addShaped(<IronChest:diamondObsidianUpgrade>, [[<ore:dustRefinedObsidian>, <ore:dustRefinedObsidian>, <ore:dustRefinedObsidian>], [<ore:dustRefinedObsidian>, <ore:gemDiamond>, <ore:dustRefinedObsidian>], [<ore:dustRefinedObsidian>, <ore:dustRefinedObsidian>, <ore:dustRefinedObsidian>]]);
recipes.addShaped(<IronChest:diamondCrystalUpgrade>, [[<ore:crystalOsmium>, <ore:crystalOsmium>, <ore:crystalOsmium>], [<ore:crystalOsmium>, <ore:gemDiamond>, <ore:crystalOsmium>], [<ore:crystalOsmium>, <ore:crystalOsmium>, <ore:crystalOsmium>]]);
recipes.addShaped(<IronChest:goldDiamondUpgrade>, [[<ore:gemDiamond>, <ore:dustDiamond>, <ore:gemDiamond>], [<ore:dustDiamond>, <ore:ingotGold>, <ore:dustDiamond>], [<ore:gemDiamond>, <ore:dustDiamond>, <ore:gemDiamond>]]);
recipes.addShaped(<IronChest:ironGoldUpgrade>, [[<ore:ingotGold>, <ore:ingotGold>, <ore:ingotGold>], [<ore:dustGold>, <ore:ingotIron>, <ore:dustGold>], [<ore:ingotGold>, <ore:ingotGold>, <ore:ingotGold>]]);
recipes.addShaped(<IronChest:silverGoldUpgrade>, [[<ore:ingotGold>, <ore:dustGold>, <ore:ingotGold>], [<ore:dustGold>, <ore:ingotSilver>, <ore:dustGold>], [<ore:ingotGold>, <ore:dustGold>, <ore:ingotGold>]]);
recipes.addShaped(<IronChest:copperIronUpgrade>, [[<ore:dustIron>, <ore:dustIron>, <ore:dustIron>], [<ore:ingotIron>, <NuclearCraft:material>, <ore:ingotIron>], [<ore:dustIron>, <ore:dustIron>, <ore:dustIron>]]);
recipes.addShaped(<IronChest:BlockIronChest>, [[<ore:dustIron>, <ore:dustIron>, <ore:dustIron>], [<ore:ingotIron>, <IronChest:BlockIronChest:3>, <ore:ingotIron>], [<ore:dustIron>, <ore:dustIron>, <ore:dustIron>]]);
recipes.addShaped(<IronChest:copperSilverUpgrade>, [[<ore:ingotSilver>, <ore:ingotSilver>, <ore:ingotSilver>], [<ore:dustSilver>, <ore:ingotCopper>, <ore:dustSilver>], [<ore:ingotSilver>, <ore:ingotSilver>, <ore:ingotSilver>]]);
recipes.addShaped(<IronChest:woodIronUpgrade>, [[<ore:ingotIron>, <ore:dustIron>, <ore:ingotIron>], [<ore:dustIron>, <ore:logWood>, <ore:dustIron>], [<ore:ingotIron>, <ore:dustIron>, <ore:ingotIron>]]);
recipes.addShaped(<IronChest:woodCopperUpgrade>, [[<ore:ingotCopper>, <ore:dustCopper>, <ore:ingotCopper>], [<ore:dustCopper>, <ore:logWood>, <ore:dustCopper>], [<ore:ingotCopper>, <ore:dustCopper>, <ore:ingotCopper>]]);
recipes.addShaped(<IronChest:BlockIronChest:5>, [[<ore:crystalOsmium>, <ore:crystalOsmium>, <ore:crystalOsmium>], [<ore:crystalOsmium>, <IronChest:BlockIronChest:2>, <ore:crystalOsmium>], [<ore:crystalOsmium>, <ore:crystalOsmium>, <ore:crystalOsmium>]]);
recipes.addShaped(<IronChest:BlockIronChest:6>, [[<ore:dustRefinedObsidian>, <ore:dustRefinedObsidian>, <ore:dustRefinedObsidian>], [<ore:dustRefinedObsidian>, <IronChest:BlockIronChest:2>, <Mekanism:OtherDust:5>], [<ore:dustRefinedObsidian>, <ore:dustRefinedObsidian>, <Mekanism:OtherDust:5>]]);
recipes.addShaped(<IronChest:BlockIronChest:1>, [[<ore:ingotGold>, <ore:ingotGold>, <ore:ingotGold>], [<ore:dustGold>, <IronChest:BlockIronChest>, <ore:dustGold>], [<ore:ingotGold>, <ore:ingotGold>, <ore:ingotGold>]]);
recipes.addShaped(<IronChest:BlockIronChest:4>, [[<ore:ingotSilver>, <ore:dustSilver>, <ore:ingotSilver>], [<ore:dustSilver>, <IronChest:BlockIronChest>, <ore:dustSilver>], [<ore:ingotSilver>, <ore:dustSilver>, <ore:ingotSilver>]]);
recipes.addShaped(<IronChest:BlockIronChest:4>, [[<ore:ingotSilver>, <ore:ingotSilver>, <ore:ingotSilver>], [<ore:dustSilver>, <IronChest:BlockIronChest:3>, <ore:dustSilver>], [<ore:ingotSilver>, <ore:ingotSilver>, <ore:ingotSilver>]]);
recipes.addShaped(<IronChest:BlockIronChest:3>, [[<ore:ingotCopper>, <ore:dustCopper>, <ore:ingotCopper>], [<ore:dustCopper>, <ore:chest>, <ore:dustCopper>], [<ore:ingotCopper>, <ore:dustCopper>, <ore:ingotCopper>]]);
recipes.addShaped(<IronChest:BlockIronChest:2>, [[<minecraft:diamond>, <Mekanism:OtherDust>, <minecraft:diamond>], [<Mekanism:OtherDust>, <IronChest:BlockIronChest:1>, <Mekanism:OtherDust>], [<minecraft:diamond>, <Mekanism:OtherDust>, <minecraft:diamond>]]);
recipes.addShaped(<IronChest:BlockIronChest:1>, [[<minecraft:gold_ingot>, <Mekanism:Dust:1>, <minecraft:gold_ingot>], [<Mekanism:Dust:1>, <IronChest:BlockIronChest:4>, <Mekanism:Dust:1>], [<minecraft:gold_ingot>, <Mekanism:Dust:1>, <minecraft:gold_ingot>]]);
recipes.addShaped(<IronChest:BlockIronChest>, [[<ore:ingotIron>, <ore:dustIron>, <ore:ingotIron>], [<ore:dustIron>, <ore:chest>, <ore:dustIron>], [<ore:ingotIron>, <ore:dustIron>, <ore:ingotIron>]]);
recipes.addShaped(<NuclearCraft:nuke>, [[<NuclearCraft:material:53>, <NuclearCraft:material:53>, <NuclearCraft:material:53>], [<NuclearCraft:material:53>, <DefenseTech:explosives:13>, <NuclearCraft:material:53>], [<NuclearCraft:material:53>, <NuclearCraft:material:53>, <NuclearCraft:material:53>]]);
recipes.addShaped(<DefenseTech:missile:15>, [[<DefenseTech:missile:23>, <NuclearCraft:nuke>]]);
recipes.addShaped(<DefenseTech:missile:21>, [[<DefenseTech:missile:23>, <NuclearCraft:antimatterBomb>]]);
recipes.addShaped(<DefenseTech:missile:27>, [[null, <NuclearCraft:nuke>, null], [<NuclearCraft:nuke>, <DefenseTech:missile:23>, <NuclearCraft:nuke>], [null, <NuclearCraft:nuke>, null]]);
recipes.addShaped(<row:item.row.stock:8>, [[<Mekanism:GasTank>, <Mekanism:GasTank>, <Mekanism:GasTank>], [<Mekanism:GasTank>, <Mekanism:GasTank>, <Mekanism:GasTank>], [<row:item.row.cartwheel>, <ore:ingotSteel>, <row:item.row.cartwheel>]]);
recipes.addShaped(<row:item.row.stock:9>, [[<Mekanism:GasTank>, <Mekanism:GasTank>, <Mekanism:GasTank>], [<row:item.row.prybar>, <Mekanism:GasTank>, <Mekanism:GasTank>], [<row:item.row.cartwheel>, <ore:ingotSteel>, <row:item.row.cartwheel>]]);
recipes.addShaped(<Mekanism:MachineBlock2>, [[<ore:blockGlassColorless>, <ore:circuitBasic>, <ore:blockGlassColorless>], [<Mekanism:GasTank>, <ore:battery>, <Mekanism:GasTank>], [<ore:blockGlassColorless>, <ore:circuitBasic>, <ore:blockGlassColorless>]]);
recipes.addShaped(<row:item.row.enginewheel>, [[<minecraft:dye:1>, <Mekanism:Ingot:4>, <minecraft:dye:1>], [<Mekanism:Ingot:4>, <flansmod:dwMidSteelIngot>, <Mekanism:Ingot:4>], [<minecraft:dye:1>, <Mekanism:Ingot:4>, <minecraft:dye:1>]]);
recipes.addShaped(<row:item.row.cartwheel>, [[null, <Mekanism:Ingot:4>, null], [<Mekanism:Ingot:4>, <minecraft:leather>, <Mekanism:Ingot:4>], [null, <Mekanism:Ingot:4>, null]]);
recipes.addShaped(<row:item.row.boiler>, [[<Mekanism:Ingot:4>, <Mekanism:Ingot:4>, <Mekanism:Ingot:4>], [<flansmod:dwMidSteelIngot>, <MekanismGenerators:Generator>, <flansmod:dwMidSteelIngot>], [<Mekanism:Ingot:4>, <Mekanism:Ingot:4>, <Mekanism:Ingot:4>]]);
recipes.addShaped(<row:item.row.funnellarge>, [[<ore:ingotSteel>, <Mekanism:Ingot:4>, <ore:ingotSteel>], [null, <Mekanism:Ingot:4>, null], [<ore:ingotSteel>, <Mekanism:Ingot:4>, <ore:ingotSteel>]]);
recipes.addShaped(<row:item.row.funnelsmall>, [[<ore:ingotSteel>], [<ore:ingotSteel>], [<ore:ingotSteel>]]);
recipes.addShaped(<row:item.row.traincabin>, [[null, <ore:ingotSteel>, <ore:ingotSteel>], [<ore:ingotSteel>, <minecraft:glass_pane>, <minecraft:iron_door>], [<ore:ingotSteel>, <ore:ingotSteel>, <ore:ingotSteel>]]);
recipes.addShaped(<row:item.row.light>, [[null, <ore:ingotSteel>, null], [<ore:ingotSteel>, <minecraft:redstone_lamp>, <ore:ingotSteel>], [null, <ore:paneGlassColorless>, null]]);
recipes.addShaped(<row:item.row.battery> * 6, [[<ore:ingotSteel>, <ore:ingotSteel>], [<ore:ingotSteel>, <flansmod:dwElectricDust>]]);
recipes.addShaped(<rowam:DetectorBlock> * 2, [[<Mekanism:BasicBlock:8>, <ore:ingotSteel>, <Mekanism:BasicBlock:8>], [<flansmod:dwHighSteelIngot>, <minecraft:detector_rail>, <flansmod:dwHighSteelIngot>], [<Mekanism:BasicBlock:8>, <ore:ingotSteel>, <Mekanism:BasicBlock:8>]]);
recipes.addShaped(<rowam:SignalBlock> * 2, [[<Mekanism:BasicBlock:8>, <ore:ingotSteel>, <Mekanism:BasicBlock:8>], [<flansmod:dwHighSteelIngot>, <DefenseTech:laserDesignator>, <flansmod:dwHighSteelIngot>], [<Mekanism:BasicBlock:8>, <ore:ingotSteel>, <Mekanism:BasicBlock:8>]]);
recipes.addShaped(<rowam:StationBlock> * 2, [[<Mekanism:BasicBlock:8>, <ore:ingotSteel>, <Mekanism:BasicBlock:8>], [<flansmod:dwHighSteelIngot>, <DefenseTech:machine:3>, <flansmod:dwHighSteelIngot>], [<Mekanism:BasicBlock:8>, <ore:ingotSteel>, <Mekanism:BasicBlock:8>]]);
recipes.addShaped(<rowam:PointerBlock> * 2, [[<Mekanism:BasicBlock:8>, <ore:ingotSteel>, <Mekanism:BasicBlock:8>], [<flansmod:dwHighSteelIngot>, <OpenComputers:waypoint>, <flansmod:dwHighSteelIngot>], [<Mekanism:BasicBlock:8>, <ore:ingotSteel>, <Mekanism:BasicBlock:8>]]);
recipes.addShaped(<rowam:FreightBlock> * 2, [[<Mekanism:BasicBlock:8>, <ore:ingotSteel>, <Mekanism:BasicBlock:8>], [<flansmod:dwHighSteelIngot>, <IronChest:BlockIronChest:1>, <flansmod:dwHighSteelIngot>], [<Mekanism:BasicBlock:8>, <ore:ingotSteel>, <Mekanism:BasicBlock:8>]]);
recipes.addShaped(<rowam:FuelingBlock> * 2, [[<Mekanism:BasicBlock:8>, <ore:ingotSteel>, <Mekanism:BasicBlock:8>], [<flansmod:dwHighSteelIngot>, <ore:blockCoal>, <flansmod:dwHighSteelIngot>], [<Mekanism:BasicBlock:8>, <ore:ingotSteel>, <Mekanism:BasicBlock:8>]]);
recipes.addShaped(<rowam:TankBlock> * 2, [[<Mekanism:BasicBlock:8>, <ore:ingotSteel>, <Mekanism:BasicBlock:8>], [<flansmod:dwHighSteelIngot>, <Mekanism:GasTank>.withTag({tier: 1}), <flansmod:dwHighSteelIngot>], [<Mekanism:BasicBlock:8>, <ore:ingotSteel>, <Mekanism:BasicBlock:8>]]);
recipes.addShaped(<minecraft:clay>, [[<ore:dyeWhite>, <minecraft:dirt>, <ore:dyeWhite>], [null, <minecraft:water_bucket>.giveBack(<minecraft:bucket>), null]]);
recipes.addShaped(<minecraft:leather>, [[<minecraft:dye:15>, <minecraft:dye:15>, <minecraft:dye:15>], [<minecraft:dye:15>, <minecraft:rotten_flesh>, <minecraft:dye:15>], [<minecraft:dye:15>, <minecraft:dye:15>, <minecraft:dye:15>]]);
recipes.addShaped(<openmodularturrets:hardWallTierFive> * 8, [[<NuclearCraft:parts:9>, <NuclearCraft:parts:8>], [<NuclearCraft:parts:8>, <NuclearCraft:parts:9>]]);
recipes.addShaped(<openmodularturrets:hardWallTierFour> * 8, [[<NuclearCraft:parts:8>, <NuclearCraft:parts:3>], [<NuclearCraft:parts:3>, <NuclearCraft:parts:8>]]);
recipes.addShaped(<openmodularturrets:hardWallTierThree> * 8, [[<NuclearCraft:parts>, <NuclearCraft:parts:3>], [<NuclearCraft:parts:3>, <NuclearCraft:parts>]]);
recipes.addShaped(<openmodularturrets:hardWallTierTwo> * 8, [[<NuclearCraft:parts>, <NuclearCraft:parts:1>], [<NuclearCraft:parts:1>, <NuclearCraft:parts>]]);
recipes.addShaped(<openmodularturrets:hardWallTierOne> * 8, [[<ore:plateTin>, <ore:plateIron>], [<ore:plateIron>, <ore:plateTin>]]);
recipes.addShaped(<powersuits:powerArmorComponent:14>, [[<ore:componentRubberHose>, <ore:componentRubberHose>, <ore:componentRubberHose>], [<ore:componentComputerChip>, <ore:circuitAdvanced>, <ore:componentComputerChip>], [<ore:componentRubberHose>, <ore:componentRubberHose>, <ore:componentRubberHose>]]);
recipes.addShaped(<powersuits:powerArmorComponent:18>, [[<flansmod:dwElectricDust>, <ore:dustRedstone>, <flansmod:dwElectricDust>], [<ore:dustRedstone>, <ore:ingotSteel>, <ore:dustRedstone>], [<flansmod:dwElectricDust>, <ore:componentSolenoid>, <flansmod:dwElectricDust>]]);
recipes.addShaped(<powersuits:powerArmorComponent:19>, [[<flansmod:dwElectricDust>, <ore:dustRedstone>, <flansmod:dwElectricDust>], [<ore:dustRedstone>, <NuclearCraft:parts:18>, <ore:dustRedstone>], [<flansmod:dwElectricDust>, <ore:dustRedstone>, <flansmod:dwElectricDust>]]);
recipes.addShaped(<powersuits:powerArmorComponent:11>, [[<ore:ingotSteel>, <Mekanism:AtomicAlloy>, <ore:ingotSteel>], [<ore:ingotSteel>, <NuclearCraft:material:7>, <ore:ingotSteel>], [null, <ore:ingotSteel>, null]]);
recipes.addShaped(<powersuits:powerArmorComponent:12>, [[<ore:ingotSteel>, <ore:oc:hologram1>, <ore:ingotSteel>]]);
recipes.addShaped(<powersuits:powerArmorComponent:15>, [[null, <ore:ingotSteel>, <minecraft:magma_cream>], [<Mekanism:Ingot:4>, <minecraft:magma_cream>, <ore:ingotSteel>], [<ore:ingotSteel>, <ore:ingotSteel>, null]]);
recipes.addShaped(<minecraft:slime_ball>, [[<minecraft:snowball>, <attainedDrops:plantSeed>]]);
recipes.addShaped(<powersuits:powerArmorComponent:20>, [[<NuclearCraft:parts:20>, <NuclearCraft:parts:20>, <NuclearCraft:parts:20>], [<NuclearCraft:parts:20>, null, <NuclearCraft:parts:20>], [<NuclearCraft:parts:20>, <NuclearCraft:parts:20>, <NuclearCraft:parts:20>]]);
recipes.addShaped(<powersuits:powerArmorComponent:17>, [[<ForgeMicroblock:sawDiamond>, <NuclearCraft:solarPanel>]]);
recipes.addShaped(<powersuits:powerArmorComponent:7>, [[null, <ore:componentWiring>, null], [<ore:componentSolenoid>, <flansmod:dwHighSteelIngot>, <ore:componentSolenoid>], [null, <ore:componentWiring>, null]]);
recipes.addShaped(<powersuits:powerArmorComponent:6>, [[null, <ore:componentWiring>, null], [<ore:componentSolenoid>, <flansmod:dwMidSteelIngot>, <ore:componentSolenoid>], [null, <ore:componentWiring>, null]]);
recipes.addShaped(<powersuits:powerArmorComponent:5>, [[null, <ore:componentWiring>, null], [<ore:componentSolenoid>, <flansmod:dwSteelIngot>, <ore:componentSolenoid>], [null, <ore:componentWiring>, null]]);
recipes.addShaped(<powersuits:powerArmorComponent:4>, [[<ore:componentWiring>, <ore:componentFieldEmitter>, <ore:componentSolenoid>], [<ore:ingotSteel>, <ore:alloyElite>, null], [<ore:componentWiring>, <ore:componentFieldEmitter>, <ore:componentSolenoid>]]);
recipes.addShaped(<powersuits:powerArmorComponent:3>, [[null, <ore:ingotSteel>, <ore:ingotSteel>], [<ore:ingotSteel>, <ore:ingotSteel>, <ore:componentSolenoid>], [<ore:ingotSteel>, null, null]]);
recipes.addShaped(<powersuits:powerArmorComponent:9>, [[<ore:plateBasic>, <NuclearCraft:parts>], [<ore:componentWiring>, <NuclearCraft:parts>], [<ore:plateBasic>, <NuclearCraft:parts>]]);
recipes.addShaped(<powersuits:powerArmorComponent:10>, [[<ore:plateReinforced>, <NuclearCraft:parts:3>], [<ore:componentWiring>, <NuclearCraft:parts:3>], [<ore:plateReinforced>, <NuclearCraft:parts:3>]]);
recipes.addShaped(<powersuits:powerArmorComponent:2>, [[null, <ore:componentSolenoid>, null], [<ore:componentWiring>, <ore:ingotSteel>, <ore:componentWiring>], [null, <ore:componentSolenoid>, null]]);
recipes.addShaped(<powersuits:powerArmorComponent> * 6, [[null, <flansmod:dwIngotBrass>, <flansmod:dwIngotBrass>], [<flansmod:dwIngotBrass>, <flansmod:dwElectricDust>, <flansmod:dwIngotBrass>], [<flansmod:dwIngotBrass>, <flansmod:dwIngotBrass>, null]]);
recipes.addShaped(<powersuits:powerArmorComponent:1>, [[<ore:componentWiring>, <ore:ingotSteel>, <ore:componentWiring>], [<ore:componentWiring>, <ore:ingotSteel>, <ore:componentWiring>], [<ore:componentWiring>, <ore:ingotSteel>, <ore:componentWiring>]]);
recipes.addShaped(<powersuits:item.powerArmorHelmet>, [[<NuclearCraft:parts:9>, <ore:circuitUltimate>, <NuclearCraft:parts:9>], [<ore:circuitElite>, <MekanismGenerators:ReactorGlass>, <ore:circuitElite>]]);
recipes.addShaped(<powersuits:item.powerArmorLeggings>, [[<NuclearCraft:parts:9>, <ore:circuitUltimate>, <NuclearCraft:parts:9>], [<Mekanism:ControlCircuit:2>, null, <Mekanism:ControlCircuit:2>], [<NuclearCraft:parts:9>, null, <NuclearCraft:parts:9>]]);
recipes.addShaped(<powersuits:item.powerArmorBoots>, [[<NuclearCraft:parts:9>, null, <ore:circuitElite>], [<NuclearCraft:parts:9>, null, <ore:plateReinforced>]]);
recipes.addShaped(<powersuits:item.powerArmorChestplate>, [[<NuclearCraft:parts:9>, null, <NuclearCraft:parts:9>], [<ore:circuitElite>, <ore:circuitUltimate>, <ore:circuitElite>], [<NuclearCraft:parts:9>, <NuclearCraft:parts:9>, <NuclearCraft:parts:9>]]);
recipes.addShaped(<powersuits:item.powerFist>, [[<ore:ingotTough>, null, <ore:ingotTough>], [<ore:ingotSteel>, <ore:ingotTough>, <ore:ingotSteel>], [<ore:componentWiring>, <ore:ingotSteel>, <ore:componentWiring>]]);
recipes.addShaped(<powersuits:tile.tinkerTable>, [[<ore:paneGlassLime>, <ore:paneGlassLime>, <ore:paneGlassLime>], [<ore:blockRefinedObsidian>, <ore:oc:hologram2>, <ore:blockRefinedObsidian>], [null, <openmodularturrets:hardWallTierFour>, null]]);
recipes.addShaped(<mffs:BlockCoercionDeriver>, [[<ore:stainedGlassBlue>, <ore:oc:hologram1>, <ore:stainedGlassBlue>], [<ore:glowstone>, <ore:gemDiamond>, <ore:glowstone>], [<Mekanism:BasicBlock:8>, <Mekanism:BasicBlock:8>, <Mekanism:BasicBlock:8>]]);
recipes.addShaped(<mffs:BlockForceFieldProjector>, [[<powersuits:powerArmorComponent:11>, <ore:oc:hologram2>, <powersuits:powerArmorComponent:11>], [<flansmod:dwHighSteelIngot>, <NuclearCraft:material:57>, <flansmod:dwHighSteelIngot>], [<Mekanism:BasicBlock:8>, <Mekanism:AtomicAlloy>, <Mekanism:BasicBlock:8>]]);
recipes.addShaped(<mffs:BlockFortronCapacitor>, [[<Mekanism:BasicBlock:8>, <mffs:focusMatrix>, <Mekanism:BasicBlock:8>], [<ore:gemDiamond>, <Mekanism:ControlCircuit:2>, <ore:gemDiamond>], [<Mekanism:BasicBlock:8>, <mffs:focusMatrix>, <Mekanism:BasicBlock:8>]]);
recipes.addShaped(<mffs:BlockInterdictionMatrix>, [[<mffs:moduleDisintegration>, <mffs:moduleDisintegration>, <mffs:moduleDisintegration>], [<mffs:focusMatrix>, <minecraft:ender_chest>, <mffs:focusMatrix>], [<ore:blockRefinedObsidian>, <ore:blockTough>, <ore:blockRefinedObsidian>]]);
recipes.addShaped(<mffs:focusMatrix> * 5, [[<flansmod:dwElectricDust>, <ore:ingotSteel>, <flansmod:dwElectricDust>], [<ore:ingotSteel>, <ore:gemDiamond>, <ore:ingotSteel>], [<flansmod:dwElectricDust>, <ore:ingotSteel>, <flansmod:dwElectricDust>]]);
recipes.addShaped(<flansmod:dwValkyrieHead>, [[<flansmod:dwSkymareArmor>, <flansmod:dwHighSteelIngot>, <flansmod:dwSkymareArmor>], [<flansmod:dwHighSteelIngot>, <minecraft:stained_glass:3>, <flansmod:dwHighSteelIngot>], [<minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 4 as short, id: 2 as short}]}), <minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 1 as short, id: 51 as short}]}), <minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 4 as short, id: 2 as short}]})]]);
recipes.addShaped(<flansmod:dwValkyrieBody>, [[<flansmod:dwHighSteelIngot>, <minecraft:potion:8258>, <flansmod:dwHighSteelIngot>], [<flansmod:dwSkymareArmor>, <flansmod:dwHighSteelIngot>, <flansmod:dwSkymareArmor>], [<flansmod:dwSkymareArmor>, <flansmod:dwHighSteelIngot>, <flansmod:dwSkymareArmor>]]);
recipes.addShaped(<flansmod:dwValkyrieBoots>, [[<minecraft:potion:8258>, null, <minecraft:potion:8258>], [<flansmod:dwSkymareArmor>, null, <flansmod:dwSkymareArmor>], [<flansmod:dwHighSteelIngot>, null, <flansmod:dwHighSteelIngot>]]);
recipes.addShaped(<flansmod:dwValkyrieLegs>, [[<flansmod:dwSkymareArmor>, <flansmod:dwHighSteelIngot>, <flansmod:dwSkymareArmor>], [<flansmod:dwHighSteelIngot>, <minecraft:potion:8258>, <flansmod:dwHighSteelIngot>], [<flansmod:dwMidSteelIngot>, null, <flansmod:dwMidSteelIngot>]]);
recipes.addShaped(<flansmod:dwContractorBody>, [[<flansmod:dwHighSteelIngot>, null, <flansmod:dwHighSteelIngot>], [<flansmod:dwSkymareArmor>, <flansmod:dwHighSteelIngot>, <flansmod:dwSkymareArmor>], [<flansmod:dwSkymareArmor>, <flansmod:dwMidSteelIngot>, <flansmod:dwSkymareArmor>]]);
recipes.addShaped(<flansmod:dwContractorHead>, [[<flansmod:dwHighSteelIngot>, <flansmod:dwMidSteelIngot>, <flansmod:dwHighSteelIngot>], [<flansmod:dwSkymareArmor>, <ore:blockGlassLightBlue>, <flansmod:dwSkymareArmor>]]);
recipes.addShaped(<flansmod:dwContractorBoots>, [[<flansmod:dwSkymareArmor>, null, <flansmod:dwSkymareArmor>], [<flansmod:dwMidSteelIngot>, null, <flansmod:dwMidSteelIngot>]]);
recipes.addShaped(<flansmod:dwContractorLegs>, [[<flansmod:dwSkymareArmor>, <flansmod:dwHighSteelIngot>, <flansmod:dwSkymareArmor>], [<flansmod:dwMidSteelIngot>, null, <flansmod:dwMidSteelIngot>], [<flansmod:dwSkymareArmor>, null, <flansmod:dwSkymareArmor>]]);
recipes.addShaped(<flansmod:dwFrostweatherBody>, [[<minecraft:wool:3>, <minecraft:wool:3>, <minecraft:wool:3>], [<minecraft:wool:3>, <flansmod:dwContractorBody>, <minecraft:wool:3>], [<minecraft:wool:3>, <minecraft:wool:3>, <minecraft:wool:3>]]);
recipes.addShaped(<flansmod:dwSpikedHead>, [[null, <ore:shardGold>, null], [null, <flansmod:dwRedwood>, null], [<flansmod:dwRedwood>, null, <flansmod:dwRedwood>]]);
recipes.addShaped(<flansmod:dwRiotHelmet>, [[<flansmod:dwMidSteelIngot>, <ore:ingotRefinedGlowstone>, <flansmod:dwMidSteelIngot>], [<flansmod:dwKipliteArmor>, <flansmod:dwBallisticGlass>, <flansmod:dwKipliteArmor>], [<NuclearCraft:material:11>, <flansmod:dwBallisticGlass>, <NuclearCraft:material:11>]]);
recipes.addShaped(<flansmod:dwPenbarHeadgear>, [[<flansmod:dwCasualHat>], [<flansmod:dwSunnyGear>]]);
recipes.addShaped(<flansmod:dwSunnyGear>, [[<ore:stainedGlassGray>, <Mekanism:Ingot:4>, <ore:stainedGlassGray>]]);
recipes.addShaped(<flansmod:dwLupineArmorStandard>, [[<flansmod:dwKipliteArmor>, null, <flansmod:dwKipliteArmor>], [<flansmod:dwMidSteelIngot>, <flansmod:dwKipliteArmor>, <flansmod:dwMidSteelIngot>], [<flansmod:dwKipliteArmor>, <Mekanism:Ingot:4>, <flansmod:dwKipliteArmor>]]);
recipes.addShaped(<flansmod:dwLupineArmorBasic>, [[<flansmod:dwKipliteArmor>, null, <flansmod:dwKipliteArmor>], [<Mekanism:Ingot:4>, <Mekanism:Ingot:4>, <Mekanism:Ingot:4>], [<Mekanism:Ingot:4>, <Mekanism:Ingot:4>, <Mekanism:Ingot:4>]]);
recipes.addShaped(<flansmod:dwLupineArmorTactical>, [[<flansmod:dwKipliteArmor>, null, <flansmod:dwKipliteArmor>], [<ore:ingotSteel>, <flansmod:dwHighSteelIngot>, <ore:ingotSteel>], [<flansmod:dwKipliteArmor>, <flansmod:dwKipliteArmor>, <flansmod:dwKipliteArmor>]]);
recipes.addShaped(<flansmod:dwLupineArmorStandardB>, [[<flansmod:dwKipliteArmor>, null, <flansmod:dwKipliteArmor>], [<ore:ingotSteel>, <ore:ingotSteel>, <ore:ingotSteel>], [<flansmod:dwKipliteArmor>, <flansmod:dwKipliteArmor>, <flansmod:dwKipliteArmor>]]);
recipes.addShaped(<flansmod:dwCasualBody>, [[<minecraft:leather>, null, <minecraft:leather>], [<flansmod:dwKipliteArmor>, <minecraft:leather>, <flansmod:dwKipliteArmor>], [<flansmod:dwKipliteArmor>, <minecraft:leather>, <flansmod:dwKipliteArmor>]]);
recipes.addShaped(<flansmod:dwCasualLegs>, [[<flansmod:dwKipliteArmor>, <flansmod:dwKipliteArmor>, <flansmod:dwKipliteArmor>], [<minecraft:leather>, null, <minecraft:leather>], [<minecraft:leather>, null, <minecraft:leather>]]);
recipes.addShaped(<flansmod:dwCasualBoots>, [[<minecraft:leather>, null, <minecraft:leather>], [<minecraft:leather>, null, <minecraft:leather>], [<flansmod:dwKipliteArmor>, null, <flansmod:dwKipliteArmor>]]);
recipes.addShaped(<flansmod:dwTacticalBoots>, [[<flansmod:dwKipliteArmor>, null, <flansmod:dwKipliteArmor>], [<minecraft:leather>, null, <minecraft:leather>]]);
recipes.addShaped(<flansmod:dwTacticalLegs>, [[<flansmod:dwKipliteArmor>, <flansmod:dwMidSteelIngot>, <flansmod:dwKipliteArmor>], [<minecraft:leather>, null, <minecraft:leather>], [<flansmod:dwMidSteelIngot>, null, <flansmod:dwMidSteelIngot>]]);
recipes.addShaped(<flansmod:dwTacticalBody>, [[<flansmod:dwMidSteelIngot>, null, <flansmod:dwMidSteelIngot>], [<flansmod:dwKipliteArmor>, <flansmod:dwMidSteelIngot>, <flansmod:dwKipliteArmor>], [<minecraft:leather>, <flansmod:dwMidSteelIngot>, <minecraft:leather>]]);
recipes.addShaped(<flansmod:dwTacticalHead>, [[<flansmod:dwMidSteelIngot>, <flansmod:dwMidSteelIngot>, <flansmod:dwMidSteelIngot>], [<flansmod:dwKipliteArmor>, <ore:stainedGlassGray>, <flansmod:dwKipliteArmor>], [<minecraft:potion:8262>, <minecraft:leather>, <minecraft:potion:8262>]]);
recipes.addShaped(<flansmod:dwGasMask>, [[<flansmod:dwKipliteArmor>, <ore:blockGlassLightBlue>, <flansmod:dwKipliteArmor>], [null, <flansmod:dwMidSteelIngot>, <RedLogic:redlogic.plainBlock:1>]]);
recipes.addShaped(<flansmod:dwChamberlainBoots>, [[<flansmod:dwKipliteArmor>, null, <flansmod:dwKipliteArmor>], [<flansmod:dwMidSteelIngot>, null, <flansmod:dwMidSteelIngot>]]);
recipes.addShaped(<flansmod:dwChamberlainLegs>, [[<flansmod:dwMidSteelIngot>, <flansmod:dwHighSteelIngot>, <flansmod:dwMidSteelIngot>], [<flansmod:dwKipliteArmor>, null, <flansmod:dwKipliteArmor>], [<flansmod:dwKipliteArmor>, null, <flansmod:dwKipliteArmor>]]);
recipes.addShaped(<flansmod:dwChamberlainBody>, [[<flansmod:dwKipliteArmor>, null, <flansmod:dwKipliteArmor>], [<flansmod:dwMidSteelIngot>, <flansmod:dwHighSteelIngot>, <flansmod:dwMidSteelIngot>], [<flansmod:dwMidSteelIngot>, <flansmod:dwMidSteelIngot>, <flansmod:dwMidSteelIngot>]]);
recipes.addShaped(<flansmod:dwChamberlainHead>, [[<flansmod:dwMidSteelIngot>, <flansmod:dwHighSteelIngot>, <flansmod:dwMidSteelIngot>], [<flansmod:dwMidSteelIngot>, <flansmod:dwGasMask>, <flansmod:dwMidSteelIngot>]]);
recipes.addShaped(<flansmod:dwAssaultBoots>, [[<flansmod:dwKipliteArmor>, null, <flansmod:dwKipliteArmor>], [<flansmod:dwKipliteArmor>, null, <flansmod:dwKipliteArmor>]]);
recipes.addShaped(<flansmod:dwAssaultLegs>, [[<flansmod:dwKipliteArmor>, <flansmod:dwKipliteArmor>, <flansmod:dwKipliteArmor>], [<flansmod:dwKipliteArmor>, null, <flansmod:dwKipliteArmor>], [<flansmod:dwKipliteArmor>, null, <flansmod:dwKipliteArmor>]]);
recipes.addShaped(<flansmod:dwAssaultBody>, [[<flansmod:dwKipliteArmor>, null, <flansmod:dwKipliteArmor>], [<flansmod:dwKipliteArmor>, <flansmod:dwKipliteArmor>, <flansmod:dwKipliteArmor>], [<flansmod:dwKipliteArmor>, <flansmod:dwKipliteArmor>, <flansmod:dwKipliteArmor>]]);
recipes.addShaped(<flansmod:dwAssaultHead>, [[<flansmod:dwKipliteArmor>, <flansmod:dwKipliteArmor>, <flansmod:dwKipliteArmor>], [<flansmod:dwKipliteArmor>, <ore:stainedGlassGray>, <flansmod:dwKipliteArmor>]]);
recipes.addShaped(<flansmod:dwWingbreakerHead>, [[<ore:blockGlassYellow>, <flansmod:dwIngotBrass>, <ore:blockGlassYellow>], [null, null, <flansmod:dwKipliteArmor>], [null, <flansmod:dwIngotBrass>, <flansmod:dwKipliteArmor>]]);
recipes.addShaped(<flansmod:dwWingbreakerBody>, [[<flansmod:dwKipliteArmor>, null, <flansmod:dwKipliteArmor>], [<flansmod:dwIngotBrass>, <flansmod:dwBrassCog>, <flansmod:dwIngotBrass>], [<flansmod:dwKipliteArmor>, <flansmod:dwKipliteArmor>, <flansmod:dwKipliteArmor>]]);
recipes.addShaped(<flansmod:dwWingbreakerLegs>, [[<flansmod:dwKipliteArmor>, <flansmod:dwKipliteArmor>, <flansmod:dwKipliteArmor>], [<flansmod:dwBrassCog>, null, <flansmod:dwBrassCog>], [<flansmod:dwIngotBrass>, null, <flansmod:dwIngotBrass>]]);
recipes.addShaped(<flansmod:dwWingbreakerBoots>, [[<flansmod:dwKipliteArmor>, null, <flansmod:dwKipliteArmor>], [<flansmod:dwIngotBrass>, null, <flansmod:dwIngotBrass>]]);
recipes.addShaped(<Mekanism:Shard:1>, [[<flansmod:dwElectricDust>, <flansmod:dwCopperPellets>, <flansmod:dwElectricDust>], [<flansmod:dwZincPellets>, <flansmod:dwElectricDust>, <flansmod:dwZincPellets>], [<flansmod:dwElectricDust>, <flansmod:dwCopperPellets>, <flansmod:dwElectricDust>]]);
recipes.addShaped(<flansmod:dwCompSteelIngot>, [[<flansmod:dwSteelIngot>, <ore:ingotGold>], [<ore:ingotIron>, <ore:ingotOsmium>]]);
recipes.addShaped(<flansmod:dwDustIron>, [[null, <ore:dustCoal>, null], [<ore:dustCoal>, <ore:ingotIron>, <ore:dustCoal>], [null, <ore:dustCoal>, null]]);
recipes.addShaped(<Mekanism:ArmoredJetpack>, [[<ore:blockTough>, <ore:ingotUranium>, <ore:blockTough>], [<ore:ingotUranium>, <Mekanism:Jetpack>, <ore:ingotUranium>], [<ore:blockTough>, <ore:ingotUranium>, <ore:blockTough>]]);
recipes.addShaped(<Mekanism:AtomicDisassembler>, [[<ore:ingotRefinedGlowstone>, <Mekanism:AtomicAlloy>, <ore:ingotRefinedGlowstone>], [<flansmod:dwHighSteelIngot>, <ore:circuitUltimate>, <flansmod:dwHighSteelIngot>], [<ore:alloyUltimate>, <ore:blockRefinedObsidian>, <ore:alloyUltimate>]]);
recipes.addShaped(<FFS:blockValve> * 2, [[<Mekanism:BasicBlock:8>, <ore:blockIron>, <Mekanism:BasicBlock:8>], [<ore:blockIron>, <minecraft:iron_bars>, <ore:blockIron>], [<Mekanism:BasicBlock:8>, <ore:blockIron>, <Mekanism:BasicBlock:8>]]);
recipes.addShaped(<Mekanism:MachineBlock2:1>, [[<ore:itemEnrichedAlloy>, <ore:ingotSteel>, <ore:itemEnrichedAlloy>], [<Mekanism:BasicBlock:9>, <MekanismGenerators:Generator:3>, <Mekanism:BasicBlock:9>], [<ore:itemEnrichedAlloy>, <ore:ingotSteel>, <ore:itemEnrichedAlloy>]]);
recipes.addShaped(<Mekanism:Robit>, [[null, <Mekanism:Ingot:4>, null], [<Mekanism:AtomicAlloy>, <OpenComputers:motionSensor>, <Mekanism:AtomicAlloy>], [<ore:ingotRefinedObsidian>, <OpenComputers:case2>, <ore:ingotRefinedObsidian>]]);
recipes.addShaped(<Mekanism:MachineBlock2:15>, [[null, <Mekanism:MachineBlock2:14>, null], [<Mekanism:MachineBlock2:14>, <ore:circuitAdvanced>, <Mekanism:MachineBlock2:14>], [null, <Mekanism:MachineBlock2:14>, null]]);
recipes.addShaped(<NuclearCraft:parts:5>, [[<ore:plateBasic>, <ore:plateBasic>, <ore:plateBasic>], [<ore:plateBasic>, <ore:universalReactant>, <ore:plateBasic>], [<ore:plateBasic>, <ore:plateBasic>, <ore:plateBasic>]]);
recipes.addShaped(<mffs:cardFrequency>, [[<flansmod:dwElectricDust>, <minecraft:paper>, <flansmod:dwElectricDust>]]);











